<OPEN_PAREN> ::= "("
<CLOSE_PAREN>::= ")"
<OPEN_BRACK> ::= "["
<CLOSE_BRACK> ::= "]"
<OPEN_BRACE> ::= "{"
<CLOSE_BRACE> ::= "}"
<DOUBLE_OPEN_BRACE> ::= "{{"
<DOUBLE_CLOSE_BRACE> ::= "}}"
<HASH> ::= "#"

<symbol> ::= "(" | ")" | "<" | ">" | "'" | '"' 
	| "=" | "|" | "." | "," | ";" | "_"
<digit> ::=  "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z"

<SPECIAL_SYMBOL> ::= "[" | "]" | "{" | "}"	
<TEXT_CHAR> ::= <letter> | <digit> | <symbol>
<char> ::= <TEXT_CHAR> | <SPECIAL_SYMBOL>
<TEXT_ESCAPE_SEQ> ::= "\"<char>
<WORD_ITEM> ::= <TEXT_CHAR> | <TEXT_ESCAPE_SEQ>

<WORD> ::= <WORD_ITEM>+

<formula> ::= <DOUBLE_OPEN_BRACE> <WORD>+ <DOUBLE_CLOSE_BRACE>
<text> ::= <WORD>+
<style_description> ::= <OPEN_BRACK> <CLOSE_BRACK>
<style_class> ::= <HASH> <WORD>
<style_scope> ::= {<style_class> | <style_description> | <style_class> <style_description>} <OPEN_BRACE> <content>+ <CLOSE_BRACE>
<content> ::= <text> | <formula> | <style_scope>

<program> ::= <content>+
